### ISSUE TITLE
event topics checkout err:if topic is zero,topics.get(0) throw IndexOutOfException

### ISSUE THREAD

**Issue by wangzxjiejie** [PlatONnetwork/client-sdk-java#63]
org.web3j.tx.Contract:staticExtractEventParameters(Event event, Log log)
 List<String> topics = log.getTopics();
        String encodedEventSignature = EventEncoder.encode(event);
        //must check topics length
        if (!((String)topics.get(0)).equals(encodedEventSignature)) {
            return null;
        } else {
            List<Type> indexedValues = new ArrayList();
            List<Type> nonIndexedValues = FunctionReturnDecoder.decode(log.getData(), event.getNonIndexedParameters());
            List<TypeReference<Type>> indexedParameters = event.getIndexedParameters();

            for(int i = 0; i < indexedParameters.size(); ++i) {
                Type value = FunctionReturnDecoder.decodeIndexedValue((String)topics.get(i + 1), (TypeReference)indexedParameters.get(i));
                indexedValues.add(value);
            }

            return new EventValues(indexedValues, nonIndexedValues);
        }

**Comment by liushuyu1** [comment]
Resolved
